version: '3.8'
services:
  hello:
    restart: unless-stopped
    image: my-app-image
    build: .
    networks:
      - node_network

  proxy:
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
    depends_on:
      - hello
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - node_network

networks:
  node_network:
